language: ruby
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
before_script:
  - psql -c 'create database apps-rdev_test;' -U postgres
rvm:
  - 2.5.3
services:
  - postgresql
  - memcached
  - redis-server
addons:
  postgresql: "9.4"
before_install:
  - gem update --system
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
